pipeline {
    agent {label 'Agent-1'}

    stages {
        stage('Git Clone') {
            steps {
                git branch: 'develop', credentialsId: 'baf06dd1-1a0c-4dd3-a7ac-8e8748f2648d',changelog: false, poll: false, url: 'https://github.com/PrinceKakadiya30/Demo-for-jenkins.git'
            }
        }

        stage('Pre Build') {
            steps {
                script {
                    sh '''
                        npm install
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                sh '''
                    npm test
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    npm run build
                '''
            }
        }
    }
}
