pipeline {
    agent {label 'Agent-1'}

    tools {
        
        git 'Default'
    }
    stages {
        stage('Git Clone') {
            steps {
                git branch: 'develop', credentialsId: 'Git-Creds-new',changelog: false, poll: false, url: 'https://github.com/PrinceKakadiya30/Demo-for-jenkins.git'
            }
        }

        stage('Pre Build') {
            steps {
                script {
                    sh '''
                        npm install
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                sh '''
                    npm test
                '''
            }
        }

        stage('Build') {
            steps {
                sh '''
                    npm run build
                '''
            }
        }
    }
}
